/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HandleMsg =
  | {
      record: {
        reminder: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      read: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
