/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InitMsg {
  /**
   * Maximum size of a reminder message in bytes
   */
  max_size: number;
  [k: string]: unknown;
}
